
spring:
  application:
    name: item-service
    
  cloud:
    config:
      overide-none: true
      
  rabbitmq:
    host: 192.168.1.111
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8801

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka